import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#2f2ebe",
        "error-container": "#93000a",
        "on-secondary": "#1000a9",
        "primary": "#ddb7ff",
        "on-error": "#690005",
        "tertiary": "#ffb0cd",
        "inverse-on-surface": "#283044",
        "outline": "#988d9f",
        "on-tertiary-fixed": "#3e0022",
        "outline-variant": "#4d4354",
        "on-tertiary": "#640039",
        "surface-container-lowest": "#060e20",
        "surface-variant": "#2d3449",
        "on-secondary-fixed": "#07006c",
        "on-surface": "#dae2fd",
        "secondary-container": "#3131c0",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#222a3d",
        "primary-fixed": "#f0dbff",
        "on-secondary-container": "#b0b2ff",
        "on-primary-container": "#400071",
        "surface-tint": "#ddb7ff",
        "on-primary-fixed-variant": "#6900b3",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "on-background": "#dae2fd",
        "on-primary-fixed": "#2c0051",
        "primary-container": "#b76dff",
        "inverse-primary": "#842bd2",
        "inverse-surface": "#dae2fd",
        "primary-fixed-dim": "#ddb7ff",
        "surface-container": "#171f33",
        "surface-dim": "#0b1326",
        "on-primary": "#490080",
        "tertiary-container": "#f751a1",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb0cd",
        "background": "#0b1326",
        "surface-container-low": "#131b2e",
        "on-tertiary-container": "#570032",
        "secondary": "#c0c1ff",
        "on-surface-variant": "#cfc2d6",
        "error": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#8c0053",
        "tertiary-fixed": "#ffd9e4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "20px",
        "section-padding": "120px",
        "container-max": "1280px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["30px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        "glow-primary": "0 0 30px 0 rgba(221,183,255,0.2)",
      },
      backgroundImage: {
        "glass-gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.15) 0%, rgba(255, 255, 255, 0.02) 100%)",
        "glow-radial": "radial-gradient(circle at center, rgba(168, 85, 247, 0.15) 0%, rgba(11, 19, 38, 0) 70%)",
      },
    },
  },
  plugins: [],
} satisfies Config;
